[package]
distribution = "2201.12.9"
name = "passenger_service"
org = "enzoj"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
name = "kafka"
org = "ballerinax"
version = "3.8.0"

[[dependency]]
name = "mongodb"
org = "ballerinax"
version = "8.0.0"

[[dependency]]
name = "crypto"
org = "ballerina"
version = "2.4.0"

[[dependency]]
name = "jwt"
org = "ballerina"
version = "2.9.0"
