[[dependency]]
name = "mongodb"
org = "ballerinax"
version = "5.0.0"

[[dependency]]
name = "kafka"
org = "ballerinax"
version = "4.0.0"

[[dependency]]
name = "http"
org = "ballerina"
version = "2.11.0"

[[dependency]]
name = "log"
org = "ballerina"
version = "2.10.0"

[[dependency]]
name = "time"
org = "ballerina"
version = "2.5.0"

[[dependency]]
name = "uuid"
org = "ballerina"
version = "1.8.0"

[[dependency]]
name = "crypto"
org = "ballerina"
version = "2.7.0"

[[dependency]]
name = "jwt"
org = "ballerina"
version = "2.13.0"

# Additional dependency for notification-service only
[[dependency]]
name = "email"
org = "ballerina"
version = "2.10.0"

# Additional dependencies for cli-client only
[[dependency]]
name = "regex"
org = "ballerina"
version = "1.5.0"

[[dependency]]
name = "runtime"
org = "ballerina"
version = "0.0.1"
