[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.0.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.0.0"

[[dependency]]
org = "ballerina"
name = "http"
version = "2.11.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.10.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.5.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.8.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.13.0"
