# Admin Service Configuration
mongoHost = "mongodb"
mongoPort = 27017
mongoUsername = "admin"
mongoPassword = "password123"
mongoDatabase = "transport_db"
transportServiceUrl = "http://transport-service:9091"
ticketingServiceUrl = "http://ticketing-service:9092"